### ISSUE TITLE
Problem login to Micro CloudFoundry

### ISSUE THREAD

**Issue by marcoalacot** [frodenas/cf-console#3]
I can't login to the Micro CloudFoundry through cf-console, I modified:

configatron.available_targets << ["VMware Micro CloudFoundry", "http://api.{Domain}.cloudfoundry.me"] 

with my domain, but I'm unable to log in with my email and password..

I'm using Ruby 1.9.3 with Rails 3.2.2,

Thanks, greetings.

**Comment by frodenas** [comment]
Marco, is this still an issue? Can you log in to your MCF?

**Comment by marcoalacot** [comment]
Yes, I reinstalled my enviroment and is working now,

Thank you.
