### ISSUE TITLE
Faraday: you may want to install system_timer for reliable timeouts

### ISSUE THREAD

**Issue by KingJames3** [frodenas/cf-console#5]
when I push cf-console to local vcap or cloudfoundry.com , is starts with error:

====> /logs/stderr.log <====

Faraday: you may want to install system_timer for reliable timeouts
/var/vcap/data/dea/apps/jcloud-console-0-32f266604128ca960cb9c7462d579379/app/rubygems/ruby/1.8/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:5:in `require': no such file to load -- fiber (LoadError)

I'm using rails 3.2.8， ruby 1.9.3

**Comment by toriq354** [comment]
I got this error too .. any solution .. ?

**Comment by frodenas** [comment]
You must use Ruby >= 1.9, so push the app with `vmc push --runtime ruby19`.
